apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: nimbupani
spec:
  postgresVersion: 17
  users:
    - name: postgres
      databases:
        - auth
        - user
        - job
        - social
        - analytics
  instances:
    - name: shard-0
      dataVolumeClaimSpec:
        storageClassName: hcloud-volume
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi

    - name: shard-1
      dataVolumeClaimSpec:
        storageClassName: hcloud-volume
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi

    - name: shard-2
      dataVolumeClaimSpec:
        storageClassName: hcloud-volume
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi

  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 5Gi
